export const EMAIL_AUDIT_ACTIONS = {
  CONNECTION_CREATED: "EMAIL_CONNECTION_CREATED",
  CONNECTION_VERIFIED: "EMAIL_CONNECTION_VERIFIED",
  CONNECTION_REVOKED: "EMAIL_CONNECTION_REVOKED",
  SENDER_CREATED: "EMAIL_SENDER_CREATED",
  SENDER_VERIFIED: "EMAIL_SENDER_VERIFIED",
  SENDER_DEFAULT_CHANGED: "EMAIL_SENDER_DEFAULT_CHANGED",
  TEMPLATE_CREATED: "EMAIL_TEMPLATE_CREATED",
  TEMPLATE_UPDATED: "EMAIL_TEMPLATE_UPDATED",
  TEMPLATE_APPROVED: "EMAIL_TEMPLATE_APPROVED",
  TEMPLATE_ARCHIVED: "EMAIL_TEMPLATE_ARCHIVED",
  TEST_RENDERED: "EMAIL_TEST_RENDERED",
  TEST_SENT: "EMAIL_TEST_SENT",
  MESSAGE_QUEUED: "EMAIL_MESSAGE_QUEUED",
  MESSAGE_SENT: "EMAIL_MESSAGE_SENT",
  MESSAGE_FAILED: "EMAIL_MESSAGE_FAILED",
  AUTOMATION_TRIGGERED: "EMAIL_AUTOMATION_TRIGGERED",
} as const;

export type EmailAuditAction = (typeof EMAIL_AUDIT_ACTIONS)[keyof typeof EMAIL_AUDIT_ACTIONS];
