"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./email-manual-composer.module.css";

type Summary={id:string;name:string;category:string;status:string;currentVersion:number};
type Variable={key:string;label:string;required:boolean;fallback?:string};
type Version={id:string;version:number;document:{subject:string;preheader:string|null;variables:Variable[]};defaultSenderIdentityId:string|null};
type Detail=Summary&{versions:Version[]};
type Sender={id:string;fromName:string;fromEmail:string;verificationStatus:string;isActive:boolean;isWorkspaceDefault:boolean};
type Runtime={runtimeEnabled:boolean;externalWritesEnabled:boolean;mode:string;internalRecipientAllowlistCount:number;manualSendEnabled:boolean};
type Audit={id:string;status:string;runtimeMode:string;subject:string;toRecipients:unknown;externalRequestSent:boolean;providerMessageId:string|null;lastError:string|null;retryOfMessageId?:string|null;createdAt:string};

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers},cache:"no-store"});const p=await r.json().catch(()=>({})) as Record<string,unknown>;if(!r.ok)throw new Error(typeof p.error==="string"?p.error:`Request failed (${r.status}).`);return p as T;}
function addresses(value:string){return value.split(/[;,]/).map(v=>v.trim()).filter(Boolean).map(email=>({email}));}
function newKey(){return `manual:${Date.now()}:${Math.random().toString(36).slice(2,10)}`;}
function toLabel(value:unknown){if(!Array.isArray(value))return "";return value.map(v=>v&&typeof v==="object"&&"email" in v?String((v as {email:unknown}).email):"").filter(Boolean).join(", ");}

export default function EmailManualComposer(){
  const [templates,setTemplates]=useState<Summary[]>([]),[senders,setSenders]=useState<Sender[]>([]),[runtime,setRuntime]=useState<Runtime|null>(null),[audits,setAudits]=useState<Audit[]>([]);
  const [templateId,setTemplateId]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[senderId,setSenderId]=useState(""),[to,setTo]=useState(""),[cc,setCc]=useState(""),[bcc,setBcc]=useState(""),[replyTo,setReplyTo]=useState("");
  const [values,setValues]=useState<Record<string,string>>({}),[idempotencyKey,setIdempotencyKey]=useState(newKey()),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{kind:"ok"|"error";text:string}|null>(null);
  const load=useCallback(async()=>{const [t,c,r,m]=await Promise.all([api<{templates:Summary[]}>("/api/email/templates"),api<{senders:Sender[]}>("/api/email/connections"),api<Runtime>("/api/email/runtime"),api<{messages:Audit[]}>("/api/email/messages?limit=12")]);setTemplates(t.templates.filter(x=>x.status==="APPROVED"));setSenders(c.senders.filter(s=>s.verificationStatus==="VERIFIED"&&s.isActive));setRuntime(r);setAudits(m.messages);},[]);
  useEffect(()=>{void load().catch(e=>setNotice({kind:"error",text:e instanceof Error?e.message:"Manual email state could not load."}));},[load]);
  useEffect(()=>{if(!templateId){setDetail(null);setValues({});return;}void api<{template:Detail}>(`/api/email/templates/${templateId}`).then(r=>{setDetail(r.template);const v=r.template.versions.find(x=>x.version===r.template.currentVersion);if(v){setSenderId(v.defaultSenderIdentityId??"");const next:Record<string,string>={};for(const variable of v.document.variables)next[variable.key]=variable.fallback??"";setValues(next);}}).catch(e=>setNotice({kind:"error",text:e instanceof Error?e.message:"Template could not load."}));},[templateId]);
  const version=useMemo(()=>detail?.versions.find(v=>v.version===detail.currentVersion)??null,[detail]);
  const canSend=Boolean(runtime?.manualSendEnabled&&version&&to.trim()&&!busy);
  async function retryMessage(messageId:string){setBusy(true);setNotice(null);try{const key=newKey();const result=await api<{message:{status:string;externalRequestSent:boolean};replayed:boolean}>(`/api/email/messages/${messageId}/retry`,{method:"POST",body:JSON.stringify({idempotencyKey:key})});setNotice({kind:"ok",text:result.message.externalRequestSent?`Retry sent. Status: ${result.message.status}.`:`Retry dry-run recorded. No external request was sent.`});await load();}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Email retry failed."});}finally{setBusy(false);}}
  async function submit(){if(!version||!detail)return;setBusy(true);setNotice(null);try{const result=await api<{message:{status:string;externalRequestSent:boolean};replayed:boolean}>("/api/email/messages/manual",{method:"POST",body:JSON.stringify({templateId:detail.id,senderIdentityId:senderId||null,to:addresses(to),cc:addresses(cc),bcc:addresses(bcc),...(replyTo.trim()?{replyTo:{email:replyTo.trim()}}:{}),variables:values,idempotencyKey})});setNotice({kind:"ok",text:result.replayed?`Idempotent replay: existing ${result.message.status} record returned.`:result.message.externalRequestSent?`Email sent. Status: ${result.message.status}.`:`Dry run recorded. No external request was sent.`});setIdempotencyKey(newKey());await load();}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Manual email failed."});}finally{setBusy(false);}}
  return <section className={styles.root} aria-label="Manual transactional email composer">
    <header className={styles.hero}><div><span>EMAIL AUTOMATION � E3</span><h2>Manual Transactional Send</h2><p>Send only approved templates through the guarded runtime. Dry-run and internal-recipient modes are the only E3 modes enabled by this composer.</p></div><div className={styles.mode} data-mode={runtime?.mode??"UNKNOWN"}><span>Runtime mode</span><strong>{runtime?.mode??"Loading"}</strong><small>{runtime?.mode==="DRY_RUN"?"Google send blocked":runtime?.mode==="INTERNAL_RECIPIENTS"?`${runtime.internalRecipientAllowlistCount} internal addresses allowed`:"Manual send locked"}</small></div></header>
    {notice?<div className={notice.kind==="ok"?styles.ok:styles.error}>{notice.text}</div>:null}
    <div className={styles.grid}><main className={styles.composer}><div className={styles.formGrid}><label>Approved template<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} � v{t.currentVersion}</option>)}</select></label><label>Sender<select value={senderId} onChange={e=>setSenderId(e.target.value)}><option value="">Template / workspace default</option>{senders.map(s=><option key={s.id} value={s.id}>{s.fromName} � {s.fromEmail}{s.isWorkspaceDefault?" � Default":""}</option>)}</select></label><label className={styles.wide}>To<input value={to} onChange={e=>setTo(e.target.value)} placeholder="recipient@example.com"/></label><label>CC<input value={cc} onChange={e=>setCc(e.target.value)} placeholder="optional"/></label><label>BCC<input value={bcc} onChange={e=>setBcc(e.target.value)} placeholder="optional"/></label><label className={styles.wide}>Reply-To<input value={replyTo} onChange={e=>setReplyTo(e.target.value)} placeholder="optional@example.com"/></label></div>
      {version?<section className={styles.vars}><div><span>PERSONALIZATION</span><strong>{version.document.subject}</strong></div>{version.document.variables.length?version.document.variables.map(v=><label key={v.key}>{v.label}{v.required?<em>Required</em>:null}<input value={values[v.key]??""} onChange={e=>setValues(x=>({...x,[v.key]:e.target.value}))} placeholder={v.fallback??`{{${v.key}}}`}/><code>{`{{${v.key}}}`}</code></label>):<p>No variables required.</p>}</section>:null}
      <div className={styles.actions}><div><span>Idempotency</span><code>{idempotencyKey}</code></div><button disabled={!canSend} onClick={()=>void submit()}>{busy?"Processing�":runtime?.mode==="DRY_RUN"?"Run dry test":runtime?.mode==="INTERNAL_RECIPIENTS"?"Send internal email":"Runtime locked"}</button></div>
    </main><aside className={styles.audit}><div className={styles.auditHead}><div><span>AUDIT LOG</span><h3>Recent manual messages</h3></div><button onClick={()=>void load()}>Reload</button></div><div className={styles.auditList}>{audits.length?audits.map(m=><article key={m.id}><div><strong>{m.subject}</strong><span>{toLabel(m.toRecipients)||"No recipient"}</span></div><em data-status={m.status}>{m.status}</em><small>{m.runtimeMode} � {m.externalRequestSent?"external request":"no external request"} � {new Date(m.createdAt).toLocaleString()}</small>{m.lastError?<p>{m.lastError}</p>:null}{m.status==="FAILED"?<button className={styles.retryButton} disabled={busy||!runtime?.manualSendEnabled} onClick={()=>void retryMessage(m.id)}>Retry failed send</button>:null}</article>):<p className={styles.empty}>No manual email audit records yet.</p>}</div></aside></div>
  </section>;
}
