"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./email-journeys.module.css";

type RuntimeState={runtimeEnabled:boolean;externalWritesEnabled:boolean;mode:string};
type Template={id:string;name:string;status:string;approvedVersionId:string|null};
type Sender={id:string;fromEmail:string;fromName:string;verificationStatus:string;isActive:boolean;isWorkspaceDefault:boolean;dailyLimit:number|null};
type Campaign={id:string;name:string;status:string;purpose:string;scheduledAt:string|null;throttlePerHour:number;frequencyCapPerDay:number;senderIdentityId:string|null;senderPool:unknown;updatedAt:string;_count?:{recipients:number}};
type CampaignState={campaigns:Campaign[]};
type TemplatesState={templates:Template[]};
type ConnectionsState={senders:Sender[]};
type FormState={name:string;purpose:"MARKETING"|"TRANSACTIONAL";templateId:string;scheduledAt:string;throttlePerHour:string;frequencyCapPerDay:string;recipients:string;contactIds:string;stage:string;tag:string;city:string};

const INITIAL:FormState={name:"",purpose:"MARKETING",templateId:"",scheduledAt:"",throttlePerHour:"100",frequencyCapPerDay:"1",recipients:"",contactIds:"",stage:"",tag:"",city:""};

async function apiJson<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers},cache:"no-store"});const payload=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(typeof payload.error==="string"?payload.error:`Request failed (${response.status}).`);return payload as T;}
function when(value:string|null){if(!value)return "Not scheduled";const date=new Date(value);return Number.isNaN(date.getTime())?"Not scheduled":new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date);}
function parseRecipients(raw:string){return raw.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const parts=line.split(",").map(v=>v.trim());if(parts[0]?.includes("@"))return{email:parts[0],name:parts[1]||undefined};return{contactId:parts[0]||undefined,email:parts[1]||"",name:parts[2]||undefined};}).filter(row=>row.email);}
function parseIds(raw:string){return Array.from(new Set(raw.split(/[\s,]+/).map(v=>v.trim()).filter(Boolean)));}

export default function EmailCampaignsWorkspace(){
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [templates,setTemplates]=useState<Template[]>([]);const [senders,setSenders]=useState<Sender[]>([]);const [runtime,setRuntime]=useState<RuntimeState|null>(null);const [form,setForm]=useState<FormState>(INITIAL);const [selectedSenders,setSelectedSenders]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const [c,t,a,r]=await Promise.all([apiJson<CampaignState>("/api/email/campaigns"),apiJson<TemplatesState>("/api/email/templates"),apiJson<ConnectionsState>("/api/email/connections"),apiJson<RuntimeState>("/api/email/runtime")]);setCampaigns(c.campaigns);setTemplates(t.templates.filter(x=>x.status==="APPROVED"&&x.approvedVersionId));setSenders(a.senders.filter(x=>x.isActive&&x.verificationStatus==="VERIFIED"));setRuntime(r);}catch(e){setError(e instanceof Error?e.message:"Campaign workspace could not be loaded.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const selectedTemplate=useMemo(()=>templates.find(t=>t.id===form.templateId)??null,[templates,form.templateId]);
  const active=campaigns.filter(c=>c.status==="ACTIVE"||c.status==="SCHEDULED").length;const paused=campaigns.filter(c=>c.status==="PAUSED").length;const recipients=campaigns.reduce((sum,c)=>sum+(c._count?.recipients??0),0);
  function toggleSender(id:string){setSelectedSenders(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
  async function createCampaign(){if(!selectedTemplate?.approvedVersionId){setError("Choose an approved template.");return;}try{setBusy("create");setError(null);setNotice(null);const segment={contactIds:parseIds(form.contactIds),stage:form.stage||undefined,tag:form.tag||undefined,city:form.city||undefined};await apiJson("/api/email/campaigns",{method:"POST",body:JSON.stringify({name:form.name,purpose:form.purpose,templateId:selectedTemplate.id,templateVersionId:selectedTemplate.approvedVersionId,senderIdentityIds:selectedSenders,scheduledAt:form.scheduledAt?new Date(form.scheduledAt).toISOString():undefined,throttlePerHour:Number(form.throttlePerHour),frequencyCapPerDay:Number(form.frequencyCapPerDay),recipients:parseRecipients(form.recipients),segment})});setForm(INITIAL);setSelectedSenders([]);setNotice("Campaign created. Delivery remains governed by the current email runtime policy.");await load();}catch(e){setError(e instanceof Error?e.message:"Campaign could not be created.");}finally{setBusy(null);}}
  async function control(campaignId:string,action:string){try{setBusy(`${campaignId}:${action}`);setError(null);setNotice(null);const result=await apiJson<Record<string,unknown>>(`/api/email/campaigns/${encodeURIComponent(campaignId)}/control`,{method:"POST",body:JSON.stringify({action,...(action==="DISPATCH"?{limit:25}:{})})});setNotice(action==="DISPATCH"?`Batch processed under ${runtime?.mode??"current"} runtime policy.`:`Campaign ${action.toLowerCase()} applied.`);void result;await load();}catch(e){setError(e instanceof Error?e.message:"Campaign action failed.");}finally{setBusy(null);}}
  if(loading)return <div className={styles.root}><div className={styles.card}><div className={styles.empty}>Loading Campaign Control Center…</div></div></div>;
  return <section className={styles.root} aria-label="Email campaigns workspace">
    <div className={styles.runtimeBar}><div className={styles.runtimeMeta}><span className={styles.chip} data-safe={runtime?.mode==="DRY_RUN"}>{runtime?.mode??"UNKNOWN"}</span><span className={styles.chip} data-safe={!runtime?.externalWritesEnabled}>{runtime?.externalWritesEnabled?"External writes enabled":"External writes protected"}</span><p>Campaign dispatch always passes consent, suppression, frequency, sender-limit and runtime gates.</p></div><button type="button" onClick={()=>void load()}>↻ Refresh</button></div>
    <div className={styles.kpis}><article><small>Total campaigns</small><strong>{campaigns.length}</strong><p>Workspace-scoped journeys</p></article><article><small>Active / scheduled</small><strong>{active}</strong><p>Eligible for scheduler processing</p></article><article><small>Paused</small><strong>{paused}</strong><p>No new campaign dispatch</p></article><article><small>Recipient executions</small><strong>{recipients}</strong><p>Per-recipient persisted state</p></article></div>
    {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
    <div className={styles.grid}>
      <section className={styles.card}><div className={styles.cardHead}><div><h2>Campaign pipeline</h2><p>Schedule, pause, resume, cancel or process guarded recipient batches.</p></div><span>{campaigns.length} campaigns</span></div><div className={styles.list}>{campaigns.length?campaigns.map(c=><article className={styles.row} key={c.id}><div className={styles.identity}><strong>{c.name}</strong><small>{c.purpose} · {when(c.scheduledAt)}</small></div><span className={styles.status} data-status={c.status}>{c.status}</span><div className={styles.metric}><b>{c._count?.recipients??0} recipients</b><small>{c.throttlePerHour}/hr · cap {c.frequencyCapPerDay}/day</small></div><div className={styles.actions}>{c.status==="PAUSED"?<button disabled={busy!==null} onClick={()=>void control(c.id,"ACTIVE")}>Resume</button>:!["COMPLETED","CANCELLED"].includes(c.status)?<button disabled={busy!==null} onClick={()=>void control(c.id,c.status==="DRAFT"?"ACTIVE":"PAUSED")}>{c.status==="DRAFT"?"Activate":"Pause"}</button>:null}{["ACTIVE","SCHEDULED"].includes(c.status)?<button disabled={busy!==null} onClick={()=>void control(c.id,"DISPATCH")}>Process 25</button>:null}{!["COMPLETED","CANCELLED"].includes(c.status)?<button data-danger="true" disabled={busy!==null} onClick={()=>void control(c.id,"CANCELLED")}>Cancel</button>:null}</div></article>):<div className={styles.empty}>No campaigns yet. Build the first guarded campaign from an approved template.</div>}</div></section>
      <section className={styles.card}><div className={styles.cardHead}><div><h3>Create campaign</h3><p>Marketing campaigns require affirmative consent and unsubscribe support at dispatch time.</p></div><span>E6</span></div><div className={styles.form}>
        <div className={styles.field}><label>Name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="September AI Workshop nurture"/></div>
        <div className={styles.two}><div className={styles.field}><label>Purpose</label><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value as FormState["purpose"]})}><option value="MARKETING">Marketing</option><option value="TRANSACTIONAL">Transactional</option></select></div><div className={styles.field}><label>Approved template</label><select value={form.templateId} onChange={e=>setForm({...form,templateId:e.target.value})}><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div></div>
        <div className={styles.field}><label>Verified sender pool</label><div className={styles.senderPool}>{senders.length?senders.map(s=><button type="button" key={s.id} data-selected={selectedSenders.includes(s.id)} onClick={()=>toggleSender(s.id)}>{s.fromEmail}{s.dailyLimit?` · ${s.dailyLimit}/day`:""}</button>):<small>No verified senders available.</small>}</div><small>Leave empty to use locked sender precedence. Multiple selections rotate across recipients.</small></div>
        <div className={styles.three}><div className={styles.field}><label>Throttle / hour</label><input type="number" min="1" max="5000" value={form.throttlePerHour} onChange={e=>setForm({...form,throttlePerHour:e.target.value})}/></div><div className={styles.field}><label>Frequency cap / day</label><input type="number" min="1" max="20" value={form.frequencyCapPerDay} onChange={e=>setForm({...form,frequencyCapPerDay:e.target.value})}/></div><div className={styles.field}><label>Schedule</label><input type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></div></div>
        <div className={styles.field}><label>Explicit recipients</label><textarea value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})} placeholder={"contactId,email,name\ncontactId,email,name"}/><small>For marketing, contactId is required at dispatch so the consent ledger can be verified.</small></div>
        <div className={styles.field}><label>CRM contact IDs</label><textarea value={form.contactIds} onChange={e=>setForm({...form,contactIds:e.target.value})} placeholder="contact-id-1, contact-id-2"/><small>Optional. If marketing contact IDs are omitted, the backend can derive the audience from latest granted EMAIL/MARKETING consent.</small></div>
        <div className={styles.three}><div className={styles.field}><label>Lead stage</label><input value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} placeholder="QUALIFIED"/></div><div className={styles.field}><label>Tag</label><input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} placeholder="AI Masterclass"/></div><div className={styles.field}><label>City</label><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Varanasi"/></div></div>
        <div className={styles.formActions}><button className={styles.primary} type="button" disabled={busy!==null||!form.name.trim()||!selectedTemplate} onClick={()=>void createCampaign()}>{busy==="create"?"Creating…":"Create guarded campaign"}</button></div>
      </div></section>
    </div>
  </section>;
}
