"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./email-journeys.module.css";

type RuntimeState={runtimeEnabled:boolean;externalWritesEnabled:boolean;mode:string};
type Template={id:string;name:string;status:string;approvedVersionId:string|null};
type Sender={id:string;fromEmail:string;verificationStatus:string;isActive:boolean};
type Sequence={id:string;name:string;status:string;purpose:string;steps:unknown;updatedAt:string;_count?:{enrollments:number}};
type StepForm={templateId:string;delayMinutes:string;senderIdentityId:string};
type FormState={name:string;purpose:"MARKETING"|"TRANSACTIONAL";steps:StepForm[]};
type EnrollForm={email:string;name:string;contactId:string};
const INITIAL:FormState={name:"",purpose:"TRANSACTIONAL",steps:[{templateId:"",delayMinutes:"0",senderIdentityId:""}]};

async function apiJson<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{...(init?.body?{"content-type":"application/json"}:{}),...init?.headers},cache:"no-store"});const payload=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(typeof payload.error==="string"?payload.error:`Request failed (${response.status}).`);return payload as T;}
function stepCount(value:unknown){return Array.isArray(value)?value.length:0;}

export default function EmailSequencesWorkspace(){
  const [sequences,setSequences]=useState<Sequence[]>([]);const [templates,setTemplates]=useState<Template[]>([]);const [senders,setSenders]=useState<Sender[]>([]);const [runtime,setRuntime]=useState<RuntimeState|null>(null);const [form,setForm]=useState<FormState>(INITIAL);const [enrollTarget,setEnrollTarget]=useState<string|null>(null);const [enroll,setEnroll]=useState<EnrollForm>({email:"",name:"",contactId:""});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const [s,t,a,r]=await Promise.all([apiJson<{sequences:Sequence[]}>("/api/email/sequences"),apiJson<{templates:Template[]}>("/api/email/templates"),apiJson<{senders:Sender[]}>("/api/email/connections"),apiJson<RuntimeState>("/api/email/runtime")]);setSequences(s.sequences);setTemplates(t.templates.filter(x=>x.status==="APPROVED"&&x.approvedVersionId));setSenders(a.senders.filter(x=>x.isActive&&x.verificationStatus==="VERIFIED"));setRuntime(r);}catch(e){setError(e instanceof Error?e.message:"Sequence workspace could not be loaded.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const templateMap=useMemo(()=>new Map(templates.map(t=>[t.id,t])),[templates]);const active=sequences.filter(s=>s.status==="ACTIVE").length;const paused=sequences.filter(s=>s.status==="PAUSED").length;const enrollments=sequences.reduce((sum,s)=>sum+(s._count?.enrollments??0),0);
  function patchStep(index:number,patch:Partial<StepForm>){setForm(current=>({...current,steps:current.steps.map((step,i)=>i===index?{...step,...patch}:step)}));}
  function addStep(){setForm(current=>({...current,steps:[...current.steps,{templateId:"",delayMinutes:"60",senderIdentityId:""}]}));}
  function removeStep(index:number){setForm(current=>({...current,steps:current.steps.filter((_,i)=>i!==index)}));}
  async function createSequence(){try{setBusy("create");setError(null);setNotice(null);const steps=form.steps.map(step=>{const template=templateMap.get(step.templateId);if(!template?.approvedVersionId)throw new Error("Every sequence step requires an approved template.");return{templateId:template.id,templateVersionId:template.approvedVersionId,delayMinutes:Number(step.delayMinutes),senderIdentityId:step.senderIdentityId||undefined};});await apiJson("/api/email/sequences",{method:"POST",body:JSON.stringify({name:form.name,purpose:form.purpose,steps})});setForm(INITIAL);setNotice("Sequence created in DRAFT. Activate it only when enrollment policy is ready.");await load();}catch(e){setError(e instanceof Error?e.message:"Sequence could not be created.");}finally{setBusy(null);}}
  async function control(sequenceId:string,action:string){try{setBusy(`${sequenceId}:${action}`);setError(null);setNotice(null);await apiJson(`/api/email/sequences/${encodeURIComponent(sequenceId)}/control`,{method:"POST",body:JSON.stringify({action})});setNotice(`Sequence ${action.toLowerCase()} applied.`);await load();}catch(e){setError(e instanceof Error?e.message:"Sequence action failed.");}finally{setBusy(null);}}
  async function enrollRecipient(){if(!enrollTarget)return;try{setBusy(`${enrollTarget}:ENROLL`);setError(null);setNotice(null);await apiJson(`/api/email/sequences/${encodeURIComponent(enrollTarget)}/control`,{method:"POST",body:JSON.stringify({action:"ENROLL",email:enroll.email,name:enroll.name||undefined,contactId:enroll.contactId||undefined})});setEnroll({email:"",name:"",contactId:""});setNotice("Recipient enrolled. Each due step will re-check suppression, consent and frequency policy.");await load();}catch(e){setError(e instanceof Error?e.message:"Recipient could not be enrolled.");}finally{setBusy(null);}}
  if(loading)return <div className={styles.root}><div className={styles.card}><div className={styles.empty}>Loading Sequence Control Center…</div></div></div>;
  return <section className={styles.root} aria-label="Email sequences workspace">
    <div className={styles.runtimeBar}><div className={styles.runtimeMeta}><span className={styles.chip} data-safe={runtime?.mode==="DRY_RUN"}>{runtime?.mode??"UNKNOWN"}</span><span className={styles.chip} data-safe={!runtime?.externalWritesEnabled}>{runtime?.externalWritesEnabled?"External writes enabled":"External writes protected"}</span><p>Sequence steps use pinned approved templates and the same guarded automation send path.</p></div><button type="button" onClick={()=>void load()}>↻ Refresh</button></div>
    <div className={styles.kpis}><article><small>Total sequences</small><strong>{sequences.length}</strong><p>Reusable lifecycle journeys</p></article><article><small>Active</small><strong>{active}</strong><p>Due enrollments can progress</p></article><article><small>Paused</small><strong>{paused}</strong><p>New sequence steps stay stopped</p></article><article><small>Enrollments</small><strong>{enrollments}</strong><p>Per-recipient execution state</p></article></div>
    {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
    <div className={styles.grid}>
      <section className={styles.card}><div className={styles.cardHead}><div><h2>Lifecycle sequences</h2><p>Activate, pause, archive and enroll recipients into reusable multi-step journeys.</p></div><span>{sequences.length} sequences</span></div><div className={styles.list}>{sequences.length?sequences.map(s=><article className={styles.row} key={s.id}><div className={styles.identity}><strong>{s.name}</strong><small>{s.purpose} · {stepCount(s.steps)} steps</small></div><span className={styles.status} data-status={s.status}>{s.status}</span><div className={styles.metric}><b>{s._count?.enrollments??0} enrollments</b><small>Persisted current step + next run</small></div><div className={styles.actions}>{s.status==="PAUSED"?<button disabled={busy!==null} onClick={()=>void control(s.id,"ACTIVE")}>Resume</button>:s.status==="DRAFT"?<button disabled={busy!==null} onClick={()=>void control(s.id,"ACTIVE")}>Activate</button>:s.status==="ACTIVE"?<button disabled={busy!==null} onClick={()=>void control(s.id,"PAUSED")}>Pause</button>:null}{s.status==="ACTIVE"?<button disabled={busy!==null} onClick={()=>setEnrollTarget(s.id)}>Enroll</button>:null}{s.status!=="ARCHIVED"?<button data-danger="true" disabled={busy!==null} onClick={()=>void control(s.id,"ARCHIVED")}>Archive</button>:null}</div></article>):<div className={styles.empty}>No sequences yet. Create a lifecycle journey from approved templates.</div>}</div>
        {enrollTarget?<div className={styles.enroll}><input value={enroll.contactId} onChange={e=>setEnroll({...enroll,contactId:e.target.value})} placeholder="Contact ID"/><input type="email" value={enroll.email} onChange={e=>setEnroll({...enroll,email:e.target.value})} placeholder="Email"/><input value={enroll.name} onChange={e=>setEnroll({...enroll,name:e.target.value})} placeholder="Name"/><button className={styles.primary} type="button" disabled={busy!==null||!enroll.email.trim()} onClick={()=>void enrollRecipient()}>{busy===`${enrollTarget}:ENROLL`?"Enrolling…":"Enroll"}</button></div>:null}
      </section>
      <section className={styles.card}><div className={styles.cardHead}><div><h3>Create sequence</h3><p>Each step pins an approved template version and optional verified sender override.</p></div><span>E6</span></div><div className={styles.form}>
        <div className={styles.two}><div className={styles.field}><label>Name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Lead nurture journey"/></div><div className={styles.field}><label>Purpose</label><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value as FormState["purpose"]})}><option value="TRANSACTIONAL">Transactional</option><option value="MARKETING">Marketing</option></select></div></div>
        <div className={styles.stepList}>{form.steps.map((step,index)=><div className={styles.step} key={index}><span className={styles.stepIndex}>{index+1}</span><div className={styles.field}><label>Approved template</label><select value={step.templateId} onChange={e=>patchStep(index,{templateId:e.target.value})}><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className={styles.field}><label>Delay (min)</label><input type="number" min="0" max="43200" value={step.delayMinutes} onChange={e=>patchStep(index,{delayMinutes:e.target.value})}/></div><div className={styles.field}><label>Sender override</label><select value={step.senderIdentityId} onChange={e=>patchStep(index,{senderIdentityId:e.target.value})}><option value="">Locked precedence</option>{senders.map(s=><option key={s.id} value={s.id}>{s.fromEmail}</option>)}</select></div><button type="button" aria-label={`Remove step ${index+1}`} disabled={form.steps.length===1} onClick={()=>removeStep(index)}>×</button></div>)}</div>
        <button className={`${styles.secondary} ${styles.addStep}`} type="button" disabled={form.steps.length>=50} onClick={addStep}>+ Add step</button><small>Marketing steps require templates that declare <code>unsubscribe_url</code>; backend validates this before creation.</small>
        <div className={styles.formActions}><button className={styles.primary} type="button" disabled={busy!==null||!form.name.trim()||form.steps.some(s=>!s.templateId)} onClick={()=>void createSequence()}>{busy==="create"?"Creating…":"Create lifecycle sequence"}</button></div>
      </div></section>
    </div>
  </section>;
}
