import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { ManualEmailSendService } from "../application/manual-send-service";
import { buildEmailTemplateRuntime } from "../infrastructure/template-runtime";
import { assertEmailBulkRecipientAllowed } from "../campaigns/campaign-service";
import { createEmailUnsubscribeUrl } from "../campaigns/unsubscribe";

function clean(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):"";}
function list(v:unknown){return Array.isArray(v)?v:[];}
function int(v:unknown,f:number,min:number,max:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.floor(n))):f;}
function json(v:unknown):Prisma.InputJsonValue{return JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue;}
function validEmail(v:unknown){const e=clean(v,320).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw new Error("A valid email address is required.");return e;}
async function assertPinned(workspaceId:string,templateId:string,versionId:string,marketing:boolean){const t=await buildEmailTemplateRuntime().service.get({workspaceId,templateId});if(t.status!=="APPROVED")throw new Error("Sequence step requires an APPROVED template.");const v=t.versions.find(x=>x.id===versionId&&x.approvedAt);if(!v)throw new Error("Sequence step templateVersionId must be the pinned approved version.");if(marketing&&!v.document.variables.some(x=>x.key==="unsubscribe_url"))throw new Error("Marketing sequence template must declare unsubscribe_url.");}
export async function createEmailSequence(input:{workspaceId:string;actorUserId:string;name:unknown;purpose?:unknown;steps:unknown}){const name=clean(input.name,160);if(name.length<3)throw new Error("Sequence name is required.");const purpose=clean(input.purpose,30).toUpperCase()==="MARKETING"?"MARKETING":"TRANSACTIONAL";const steps=list(input.steps).slice(0,50).map((raw,index)=>{const r=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const templateId=clean(r.templateId,100),templateVersionId=clean(r.templateVersionId,100);if(!templateId||!templateVersionId)throw new Error(`Sequence step ${index+1} requires templateId and templateVersionId.`);return{delayMinutes:int(r.delayMinutes,index===0?0:60,0,43_200),templateId,templateVersionId,senderIdentityId:clean(r.senderIdentityId,100)||null};});if(!steps.length)throw new Error("Sequence requires at least one step.");for(const step of steps)await assertPinned(input.workspaceId,step.templateId,step.templateVersionId,purpose==="MARKETING");return prisma.engageEmailSequence.create({data:{workspaceId:input.workspaceId,name,status:"DRAFT",purpose,steps:json(steps),createdById:input.actorUserId}});}
export async function listEmailSequences(workspaceId:string){return prisma.engageEmailSequence.findMany({where:{workspaceId},orderBy:{updatedAt:"desc"},take:100,include:{_count:{select:{enrollments:true}}}});}
export async function setEmailSequenceStatus(input:{workspaceId:string;sequenceId:string;status:"ACTIVE"|"PAUSED"|"ARCHIVED"}){const row=await prisma.engageEmailSequence.findFirst({where:{id:input.sequenceId,workspaceId:input.workspaceId}});if(!row)throw new Error("Sequence not found.");if(row.status==="ARCHIVED")throw new Error("Archived sequence cannot be reactivated.");return prisma.engageEmailSequence.update({where:{id:row.id},data:{status:input.status}});}
export async function enrollEmailSequence(input:{workspaceId:string;sequenceId:string;contactId?:unknown;email:unknown;name?:unknown}){const s=await prisma.engageEmailSequence.findFirst({where:{id:input.sequenceId,workspaceId:input.workspaceId}});if(!s||s.status!=="ACTIVE")throw new Error("Active sequence not found.");const address=validEmail(input.email),contactId=clean(input.contactId,100)||null;if(s.purpose==="MARKETING")await assertEmailBulkRecipientAllowed({workspaceId:input.workspaceId,purpose:"MARKETING",recipient:{contactId,email:address,name:clean(input.name,160)||null},frequencyCapPerDay:1});const steps=list(s.steps);const first=steps[0]&&typeof steps[0]==="object"&&!Array.isArray(steps[0])?steps[0] as Record<string,unknown>:{};const nextRunAt=new Date(Date.now()+int(first.delayMinutes,0,0,43_200)*60_000);return prisma.engageEmailSequenceEnrollment.upsert({where:{sequenceId_email:{sequenceId:s.id,email:address}},update:{status:"ACTIVE",currentStep:0,nextRunAt,lastError:null,contactId,name:clean(input.name,160)||null},create:{workspaceId:input.workspaceId,sequenceId:s.id,contactId,email:address,name:clean(input.name,160)||null,status:"ACTIVE",currentStep:0,nextRunAt}});}
export async function processDueEmailSequences(limit=50){const due=await prisma.engageEmailSequenceEnrollment.findMany({where:{status:"ACTIVE",nextRunAt:{lte:new Date()},sequence:{status:"ACTIVE"}},include:{sequence:true},orderBy:{nextRunAt:"asc"},take:Math.min(Math.max(limit,1),100)});let processed=0,failed=0,completed=0;for(const e of due){try{const steps=list(e.sequence.steps);const raw=steps[e.currentStep];if(!raw||typeof raw!=="object"||Array.isArray(raw)){await prisma.engageEmailSequenceEnrollment.update({where:{id:e.id},data:{status:"COMPLETED"}});completed++;continue;}const step=raw as Record<string,unknown>;if(e.sequence.purpose==="MARKETING")await assertEmailBulkRecipientAllowed({workspaceId:e.workspaceId,purpose:"MARKETING",recipient:{contactId:e.contactId,email:e.email,name:e.name},frequencyCapPerDay:1});const variables:Record<string,string>={contactId:e.contactId??"",sequenceName:e.sequence.name};if(e.sequence.purpose==="MARKETING"){if(!e.contactId)throw new Error("Marketing sequence contactId is required.");variables.unsubscribe_url=createEmailUnsubscribeUrl({workspaceId:e.workspaceId,contactId:e.contactId,email:e.email});}const result=await new ManualEmailSendService().send({workspaceId:e.workspaceId,templateId:clean(step.templateId,100),templateVersionId:clean(step.templateVersionId,100),automationSenderIdentityId:clean(step.senderIdentityId,100)||null,to:[{email:e.email,...(e.name?{name:e.name}:{})}],variables,idempotencyKey:`sequence:${e.id}:step:${e.currentStep}`,actorUserId:e.sequence.createdById,deliveryContext:"AUTOMATION"});const next=e.currentStep+1,nraw=steps[next];const done=!nraw;const nr=nraw&&typeof nraw==="object"&&!Array.isArray(nraw)?nraw as Record<string,unknown>:{};await prisma.$transaction(async tx=>{await tx.engageEmailSequenceEnrollment.update({where:{id:e.id},data:done?{status:"COMPLETED",currentStep:next,lastError:null}:{currentStep:next,nextRunAt:new Date(Date.now()+int(nr.delayMinutes,60,0,43_200)*60_000),lastError:null}});await tx.engageEmailAnalyticsEvent.upsert({where:{workspaceId_eventKey:{workspaceId:e.workspaceId,eventKey:`sequence:${e.id}:${e.currentStep}:${result.message.id}`}},update:{},create:{workspaceId:e.workspaceId,messageId:result.message.id,contactId:e.contactId,eventType:result.message.externalRequestSent?"SEQUENCE_SENT":"SEQUENCE_DRY_RUN",provider:null,eventKey:`sequence:${e.id}:${e.currentStep}:${result.message.id}`,metadata:json({sequenceId:e.sequenceId,step:e.currentStep,email:e.email}),occurredAt:new Date()}});});processed++;if(done)completed++;}catch(error){failed++;await prisma.engageEmailSequenceEnrollment.update({where:{id:e.id},data:{status:"FAILED",lastError:error instanceof Error?error.message:"Sequence execution failed."}});}}return{processed,failed,completed};}
