import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requireEmailManagerAccess, EmailDashboardAccessError } from "@/modules/email-automation/application/dashboard-access";
import { ManualEmailSendService } from "@/modules/email-automation/application/manual-send-service";
import { buildEmailReadRuntime } from "@/modules/email-automation/infrastructure/runtime";
import { resolveEmailSender } from "@/modules/email-automation/domain/sender-resolution";
import type { EmailAddress } from "@/modules/email-automation/domain/contracts";
export const runtime="nodejs"; export const dynamic="force-dynamic";
function addresses(value:unknown):EmailAddress[]{if(!Array.isArray(value))return[];return value.flatMap((v)=>{if(typeof v==="string")return v.includes("@")?[{email:v.trim()}]:[];if(!v||typeof v!=="object"||Array.isArray(v))return[];const r=v as Record<string,unknown>;return typeof r.email==="string"?[{email:r.email,...(typeof r.name==="string"?{name:r.name}:{})}]:[];});}
function one(value:unknown):EmailAddress|null{if(typeof value==="string"&&value.includes("@"))return{email:value.trim()};if(value&&typeof value==="object"&&!Array.isArray(value)){const r=value as Record<string,unknown>;if(typeof r.email==="string")return{email:r.email,...(typeof r.name==="string"?{name:r.name}:{})};}return null;}
function dedupe(items:EmailAddress[],exclude:string[]=[]){const blocked=new Set(exclude.map(x=>x.toLowerCase()));const seen=new Set<string>();return items.filter(x=>{const k=x.email.trim().toLowerCase();if(!k||blocked.has(k)||seen.has(k))return false;seen.add(k);return true;});}
export async function POST(request:Request){try{const a=await requireEmailManagerAccess();const b=await request.json() as Record<string,unknown>;if(typeof b.inboundMessageId!=="string"||typeof b.templateId!=="string"||typeof b.idempotencyKey!=="string")return NextResponse.json({error:"inboundMessageId, templateId and idempotencyKey are required."},{status:400});const inbound=await prisma.engageEmailInboundMessage.findFirst({where:{id:b.inboundMessageId,workspaceId:a.workspaceId}});if(!inbound)return NextResponse.json({error:"Inbound email not found."},{status:404});const runtime=buildEmailReadRuntime();const senders=await runtime.senders.listByWorkspace(a.workspaceId);const resolved=resolveEmailSender({availableSenders:senders,manualSenderIdentityId:typeof b.senderIdentityId==="string"?b.senderIdentityId:null,automationSenderIdentityId:null,templateSenderIdentityId:null});const replyTarget=one(inbound.replyTo)||{email:inbound.fromAddress};const replyAll=b.replyAll===true;const cc=replyAll?dedupe([...addresses(inbound.toRecipients),...addresses(inbound.ccRecipients)],[replyTarget.email,resolved.sender.fromEmail]):[];const result=await new ManualEmailSendService().send({workspaceId:a.workspaceId,templateId:b.templateId,templateVersionId:typeof b.templateVersionId==="string"?b.templateVersionId:null,manualSenderIdentityId:typeof b.senderIdentityId==="string"?b.senderIdentityId:null,to:[replyTarget],cc,variables:b.variables&&typeof b.variables==="object"&&!Array.isArray(b.variables)?b.variables as Record<string,string|null|undefined>:{},idempotencyKey:b.idempotencyKey,actorUserId:a.user.id,subjectOverride:typeof b.subjectOverride==="string"?b.subjectOverride:null,htmlOverride:typeof b.htmlOverride==="string"?b.htmlOverride:null,textOverride:typeof b.textOverride==="string"?b.textOverride:null,providerThreadId:inbound.providerThreadId});return NextResponse.json(result,{status:result.replayed?200:201,headers:{"cache-control":"no-store"}});}catch(e){if(e instanceof EmailDashboardAccessError)return NextResponse.json({error:e.message},{status:e.status});return NextResponse.json({error:e instanceof Error?e.message:"Email reply failed."},{status:400});}}