#!/usr/bin/env bash
set -Eeuo pipefail

activate="scripts/email-inbound-production-activate.sh"
runner="scripts/email-inbound-production-activate.ts"
readiness="scripts/email-inbound-production-readiness.ts"
service="modules/email-automation/inbound/gmail-inbound-service.ts"
connect_route="app/api/email/google/connect/route.ts"
connection_service="modules/email-automation/application/connection-service.ts"
credential_vault="modules/email-automation/infrastructure/prisma-credential-vault.ts"
accounts_ui="modules/email-automation/ui/EmailSenderManager.tsx"
workflow="../../.github/workflows/whatsapp-agent-email-inbound-activate.yml"
readiness_workflow="../../.github/workflows/whatsapp-agent-email-inbound-readiness.yml"

for file in "$activate" "$runner" "$readiness" "$service" "$connect_route" "$connection_service" "$credential_vault" "$accounts_ui" "$workflow" "$readiness_workflow"; do test -f "$file"; done
bash -n "$activate"
grep -Fq 'Email send runtime must remain DRY_RUN' "$activate"
grep -Fq 'Email external writes must remain disabled' "$activate"
grep -Fq 'EMAIL_INBOUND_SYNC_ENABLED' "$activate"
grep -Fq 'EMAIL_GMAIL_INBOUND_MODE' "$activate"
grep -Fq 'POLLING' "$activate"
grep -Fq 'WATCH' "$activate"
grep -Fq 'FAILED_EMAIL_INBOUND_ACTIVATION_ROLLED_BACK' "$activate"
grep -Fq 'inboundSyncEnabled!==true' "$activate"
grep -Fq 'systemctl is-active --quiet sikhadenge-email-automation-scheduler.timer' "$activate"
grep -Fq 'stage="verify-inbound-oauth-access"' "$activate"
grep -Fq 'email-inbound-production-readiness.ts' "$activate"
readiness_line="$(grep -n 'email-inbound-production-readiness.ts' "$activate" | head -n1 | cut -d: -f1)"
enable_line="$(grep -n 'stage="enable-inbound-flag"' "$activate" | head -n1 | cut -d: -f1)"
[[ -n "$readiness_line" && -n "$enable_line" && "$readiness_line" -lt "$enable_line" ]] || { echo 'Inbound OAuth readiness must run before enabling the production inbound flag.' >&2; exit 1; }
grep -Fq 'EMAIL_RUNTIME_MODE' "$runner"
grep -Fq 'DRY_RUN' "$runner"
grep -Fq 'EMAIL_EXTERNAL_WRITES_ENABLED' "$runner"
grep -Fq 'bootstrapGmailHistoryCursor' "$runner"
grep -Fq 'GOOGLE_GMAIL_PUBSUB_TOPIC is required in WATCH mode' "$runner"
grep -Fq 'EMAIL_GMAIL_INBOUND_MODE' "$readiness"
grep -Fq 'inboundMode !== "WATCH" || checks.pubSubTopic' "$readiness"
grep -Fq 'support@sikhadenge.in' "$readiness"
grep -Fq '(connection.displayName ?? "").trim().toLowerCase() !== activationAccount' "$readiness"
grep -Fq '(connection.displayName ?? "").trim().toLowerCase() !== allowedAccount' "$runner"
grep -Fq 'profile?.emailAddress?.trim().toLowerCase()' "$readiness"
grep -Fq 'profile.emailAddress?.trim().toLowerCase()' "$runner"
grep -Fq 'Authenticated Gmail mailbox' "$readiness"
grep -Fq 'Authenticated Gmail mailbox' "$runner"
grep -Fq 'authenticatedAccount,' "$runner"
grep -Fq 'authenticatedAccount: row.displayName' "$readiness"
grep -Fq 'gmailInboundReadAccess' "$readiness"
grep -Fq 'gmailHistoryReadAccess' "$readiness"
grep -Fq 'safeSendRuntime' "$readiness"
grep -Fq 'Outbound Email runtime must remain DRY_RUN with external writes disabled' "$readiness"
grep -Fq 'gmailInboundScopeGranted' "$readiness"
grep -Fq 'GMAIL_INBOUND_SCOPES' "$readiness"
grep -Fq 'gmailGrantedScopes' "$readiness"
grep -Fq 'missing required scope' "$readiness"
grep -Fq 'getGrantedScopesForConnection' "$readiness"
grep -Fq 'OAUTH_SCOPES' "$credential_vault"
grep -Fq 'JSON.stringify([...new Set(input.credentials.scopes)])' "$credential_vault"
grep -Fq 'kind: OAUTH_SCOPES_KIND' "$credential_vault"
grep -Fq 'scopes,' "$credential_vault"
grep -Fq 'https://gmail.googleapis.com/gmail/v1/users/me/profile' "$readiness"
grep -Fq 'https://gmail.googleapis.com/gmail/v1/users/me/history' "$readiness"
grep -Fq 'historyTypes", "messageAdded"' "$readiness"
grep -Fq 'maxResults", "1"' "$readiness"
grep -Fq 'Gmail history.list read access failed' "$readiness"
grep -Fq 'https://gmail.googleapis.com/gmail/v1/users/me/history' "$runner"
grep -Fq 'Gmail history.list verification failed' "$runner"
grep -Fq 'historyReadVerified: true' "$runner"
grep -Fq 'Enable Inbox Access' "$readiness"
grep -Fq 'bootstrapGmailHistoryCursor' "$service"
grep -Fq 'https://gmail.googleapis.com/gmail/v1/users/me/profile' "$service"
grep -Fq 'syncMode: "POLLING"' "$service"
grep -Fq 'syncMode: "WATCH"' "$service"
grep -Fq 'enableInbound' "$connect_route"
grep -Fq 'GMAIL_INBOUND_SCOPES' "$connect_route"
grep -Fq 'include_granted_scopes' "$connect_route"
grep -Fq 'prompt", "consent"' "$connect_route"
grep -Fq 'workspaceConnections.find' "$connection_service"
grep -Fq 'connection.externalAccountId === oauth.externalAccountId' "$connection_service"
grep -Fq 'oauth.credentials.refreshToken ?? previousCredentials?.refreshToken' "$connection_service"
grep -Fq 'Enable Inbox Access' "$accounts_ui"
grep -Fq 'JSON.stringify({enableInbound:true})' "$accounts_ui"
grep -Fq 'support@sikhadenge.in' "$workflow"
grep -Fq "[email-inbound-activate]" "$workflow"
grep -Fq 'workflow_dispatch:' "$workflow"
grep -Fq 'deployed_sha:' "$workflow"
grep -Fq "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[email-inbound-activate]')" "$workflow"
grep -Fq 'DEPLOYED_SHA: ${{ github.event_name ==' "$workflow"
grep -Fq 'inputs.deployed_sha || github.event.before }}' "$workflow"
grep -Fq 'workflow_dispatch:' "$readiness_workflow"
grep -Fq 'deployed_sha:' "$readiness_workflow"
grep -Fq 'apps/whatsapp-agent-dashboard/docs/email-inbound-live-readiness-trigger.md' "$readiness_workflow"
grep -Fq 'group: whatsapp-agent-email-inbound-readiness' "$readiness_workflow"
grep -Fq 'REQUESTED_DEPLOYED_SHA: ${{ github.event_name ==' "$readiness_workflow"
grep -Fq "inputs.deployed_sha || '' }}" "$readiness_workflow"
grep -Fq 'engageos-github-*/post-deploy-evidence.txt' "$readiness_workflow"
grep -Fq 'RUNTIME_STABLE_EXIT_CODE' "$readiness_workflow"
if grep -Eq 'EMAIL_RUNTIME_MODE=(LIVE|LIMITED_COHORT|INTERNAL_RECIPIENTS)|EMAIL_EXTERNAL_WRITES_ENABLED=true' "$activate"; then
  echo 'Inbound activation must never widen outbound email delivery mode.' >&2
  exit 1
fi
printf 'Email E5 production inbound safety policy: PASS\n'
