import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { EmailSenderIdentity } from "../domain/contracts";
import { renderEmailTemplate } from "../templates/render";
import { assertEmailTemplateDocument } from "../templates/validation";
import { microsoftEmailProviderConfigFromEnv } from "../providers/microsoft/config";
import { emailProviderFailoverPolicyFromEnv, selectFailoverSender } from "../providers/routing/failover-policy";
import { createEmailUnsubscribeToken, verifyEmailUnsubscribeToken } from "../campaigns/unsubscribe";
import { selectUniqueWorkspaceContactId } from "../analytics/contact-attribution-contract";

const htmlDoc={subject:"Hello {{name}}",preheader:null,variables:[{key:"name",label:"Name",required:true}],blocks:[{id:"html",type:"HTML" as const,html:"<div><strong>Hello {{name}}</strong></div>",text:"Hello {{name}}"}]};
assertEmailTemplateDocument(htmlDoc);const rendered=renderEmailTemplate({document:htmlDoc,values:{name:"Ankit"}});assert.match(rendered.html,/Hello Ankit/);
assert.throws(()=>assertEmailTemplateDocument({...htmlDoc,blocks:[{id:"bad",type:"HTML" as const,html:"<script>alert(1)</script>",text:"bad"}]}),/unsafe html/i);
assert.throws(()=>microsoftEmailProviderConfigFromEnv({} as unknown as NodeJS.ProcessEnv),/not configured/i);
assert.equal(microsoftEmailProviderConfigFromEnv({MICROSOFT_EMAIL_CLIENT_ID:"id",MICROSOFT_EMAIL_CLIENT_SECRET:"secret",MICROSOFT_EMAIL_TENANT_ID:"tenant",MICROSOFT_EMAIL_OAUTH_STATE_SECRET:"x".repeat(32)} as unknown as NodeJS.ProcessEnv).tenantId,"tenant");
process.env.EMAIL_UNSUBSCRIBE_SECRET="u".repeat(32);const token=createEmailUnsubscribeToken({workspaceId:"w1",contactId:"c1",email:"User@Example.com",expiresAt:new Date(Date.now()+60000)});assert.equal(verifyEmailUnsubscribeToken(token).email,"user@example.com");assert.throws(()=>verifyEmailUnsubscribeToken(token.slice(0,-1)+(token.endsWith("a")?"b":"a")),/signature|malformed/i);
const sender=(id:string,provider:EmailSenderIdentity["provider"],verified=true):EmailSenderIdentity=>({id,workspaceId:"w",connectionId:id+"-c",provider,fromName:id,fromEmail:id+"@example.com",replyToEmail:null,externalSenderId:null,verificationStatus:verified?"VERIFIED":"FAILED",isProviderDefault:false,isWorkspaceDefault:false,isActive:true,dailyLimit:null});
const primary=sender("g","GOOGLE_GMAIL"),microsoft=sender("m","MICROSOFT_365"),bad=sender("bad","MICROSOFT_365",false);assert.equal(selectFailoverSender({policy:emailProviderFailoverPolicyFromEnv({} as unknown as NodeJS.ProcessEnv),primary,senders:[microsoft]}),null);const policy=emailProviderFailoverPolicyFromEnv({EMAIL_PROVIDER_FAILOVER_ENABLED:"true",EMAIL_PROVIDER_FAILOVER_ORDER:"GOOGLE_GMAIL,MICROSOFT_365"} as unknown as NodeJS.ProcessEnv);assert.equal(selectFailoverSender({policy,primary,senders:[bad,microsoft]})?.id,"m");
assert.equal(selectUniqueWorkspaceContactId([null,undefined," c1 ","c1"]),"c1");
assert.equal(selectUniqueWorkspaceContactId(["c1","c2"]),null);
assert.equal(selectUniqueWorkspaceContactId([null,"  "]),null);
const schedulerSource=readFileSync("modules/email-automation/automation/scheduler.ts","utf8");
assert.match(schedulerSource,/processDueEmailSequences\s*\}\s*from\s*"\.\.\/sequences\/sequence-service"/);
assert.doesNotMatch(schedulerSource,/processDueEmailSequences\s*\}\s*from\s*"\.\.\/finalization\/platform-service"/);

const emailNavSource=readFileSync("modules/email-automation/ui/EmailWorkspaceNav.tsx","utf8");
const campaignPageSource=readFileSync("app/email/campaigns/page.tsx","utf8");
const sequencePageSource=readFileSync("app/email/sequences/page.tsx","utf8");
const campaignUiSource=readFileSync("modules/email-automation/ui/EmailCampaignsWorkspace.tsx","utf8");
const sequenceUiSource=readFileSync("modules/email-automation/ui/EmailSequencesWorkspace.tsx","utf8");
assert.match(emailNavSource,/\["Campaigns",\s*"\/email\/campaigns"/);
assert.match(emailNavSource,/\["Sequences",\s*"\/email\/sequences"/);
assert.match(campaignPageSource,/EmailCampaignsWorkspace/);
assert.match(sequencePageSource,/EmailSequencesWorkspace/);
for(const route of ["\/api\/email\/campaigns","\/api\/email\/templates","\/api\/email\/connections","\/api\/email\/runtime"]) assert.match(campaignUiSource,new RegExp(route));
assert.match(campaignUiSource,/control\(c\.id,\s*"DISPATCH"\)/);
assert.match(campaignUiSource,/result\.waiting===true/);
assert.match(campaignUiSource,/result\.processed/);
assert.match(campaignUiSource,/result\.failed/);
assert.match(campaignUiSource,/result\.remaining/);
assert.match(campaignUiSource,/Campaign batch completed with recipient failures/);
assert.match(sequenceUiSource,/\/api\/email\/sequences/);
assert.match(sequenceUiSource,/action:\s*"ENROLL"/);
assert.match(sequenceUiSource,/"PAUSED"/);
assert.match(sequenceUiSource,/"ARCHIVED"/);
const platformSource=readFileSync("modules/email-automation/finalization/platform-service.ts","utf8");
const attributionSource=readFileSync("modules/email-automation/analytics/workspace-safe-attribution.ts","utf8");
const dispatcherSource=readFileSync("modules/email-automation/automation/dispatcher.ts","utf8");
const campaignServiceSource=readFileSync("modules/email-automation/campaigns/campaign-service.ts","utf8");
const sequenceServiceSource=readFileSync("modules/email-automation/sequences/sequence-service.ts","utf8");
const schemaSource=readFileSync("prisma/schema.prisma","utf8");
const trackingIndexMigrationSource=readFileSync("prisma/migrations/20260919132000_add_email_tracking_message_indexes/migration.sql","utf8");
const trackingStart=platformSource.indexOf("export async function recordEmailAnalyticsEvent");
const trackingEnd=platformSource.indexOf("export async function emailAnalyticsOverview",trackingStart);
const trackingSource=platformSource.slice(trackingStart,trackingEnd);
assert.match(trackingSource,/resolveWorkspaceSafeTrackingContactId/);
assert.doesNotMatch(trackingSource,/whatsAppContact\.findFirst/);
assert.match(attributionSource,/workspaceId:\s*input\.workspaceId/);
assert.match(attributionSource,/messageId:\s*input\.messageId/);
assert.match(attributionSource,/TRUSTED_SEND_EVENT_TYPES/);
assert.match(attributionSource,/engageEmailCampaignRecipient\.findMany/);
assert.match(dispatcherSource,/"AUTOMATION_SENT"/);
assert.match(dispatcherSource,/"AUTOMATION_DRY_RUN"/);
assert.match(dispatcherSource,/engageEmailAnalyticsEvent\.upsert/);
assert.match(platformSource,/update:contactId\?\{contactId\}:\{\}/);
assert.match(attributionSource,/backfillWorkspaceTrackingContactId/);
assert.match(attributionSource,/eventType:\s*\{\s*in:\s*\["OPENED",\s*"CLICKED",\s*"DELIVERED"\]\s*\}/);
assert.match(attributionSource,/contactId:\s*null/);
assert.match(campaignServiceSource,/backfillWorkspaceTrackingContactId/);
assert.match(sequenceServiceSource,/backfillWorkspaceTrackingContactId/);
assert.match(dispatcherSource,/backfillWorkspaceTrackingContactId/);
assert.match(schemaSource,/model EngageEmailCampaignRecipient[\s\S]*@@index\(\[workspaceId, messageId\]\)/);
assert.match(schemaSource,/model EngageEmailAnalyticsEvent[\s\S]*@@index\(\[workspaceId, messageId\]\)/);
assert.match(trackingIndexMigrationSource,/EngageEmailCampaignRecipient_workspaceId_messageId_idx/);
assert.match(trackingIndexMigrationSource,/EngageEmailAnalyticsEvent_workspaceId_messageId_idx/);
console.log("email platform finalization contracts: ok");
