import { createHash, randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { ManualEmailSendService } from "../application/manual-send-service";
import { enqueueEmailAutomationEvent, supersedePendingEmailAutomationEvents } from "../automation/event-outbox";
import { EMAIL_PROVIDERS } from "../domain/contracts";
import { resolveWorkspaceSafeTrackingContactId } from "../analytics/workspace-safe-attribution";

function json(value: unknown): Prisma.InputJsonValue { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
function clean(value: unknown, max = 500): string { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function email(value: unknown): string { const v=clean(value,320).toLowerCase(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)) throw new Error("A valid email address is required."); return v; }
function int(value: unknown, fallback: number, min: number, max: number): number { const n=Number(value); return Number.isFinite(n) ? Math.min(max,Math.max(min,Math.floor(n))) : fallback; }
function arr(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function eventKey(parts: readonly string[]): string { return createHash("sha256").update(parts.join("|")).digest("hex"); }

export async function getEmailPlatformOverview(workspaceId: string) {
  const [inbound,campaigns,sequences,analytics,messages,automationEvents,connections] = await Promise.all([
    prisma.engageEmailInboundMessage.count({where:{workspaceId}}), prisma.engageEmailCampaign.count({where:{workspaceId}}),
    prisma.engageEmailSequence.count({where:{workspaceId}}), prisma.engageEmailAnalyticsEvent.count({where:{workspaceId}}),
    prisma.engageEmailMessage.groupBy({by:["status"],where:{workspaceId},_count:{_all:true}}),
    prisma.engageEmailAutomationEvent.groupBy({by:["status"],where:{workspaceId},_count:{_all:true}}),
    prisma.engageChannelConnection.findMany({where:{workspaceId,channel:{startsWith:"EMAIL"}},select:{id:true,externalAccountId:true,displayName:true,status:true,capabilities:true}}),
  ]);
  const providerReadiness = EMAIL_PROVIDERS.map((provider)=>({provider,configured: provider==="GOOGLE_GMAIL" ? Boolean(process.env.GOOGLE_GMAIL_CLIENT_ID&&process.env.GOOGLE_GMAIL_CLIENT_SECRET) : provider==="MICROSOFT_365" ? Boolean(process.env.MICROSOFT_EMAIL_CLIENT_ID&&process.env.MICROSOFT_EMAIL_CLIENT_SECRET&&process.env.MICROSOFT_EMAIL_TENANT_ID) : false,registered: provider==="GOOGLE_GMAIL" || provider==="MICROSOFT_365"}));
  return {inbound,campaigns,sequences,analytics,messages:Object.fromEntries(messages.map(x=>[x.status,x._count._all])),automationEvents:Object.fromEntries(automationEvents.map(x=>[x.status,x._count._all])),connections,providerReadiness,guards:{inboundSyncEnabled:process.env.EMAIL_INBOUND_SYNC_ENABLED==="true",trackingEnabled:process.env.EMAIL_TRACKING_ENABLED==="true",gmailPubSubTopic:Boolean(process.env.GOOGLE_GMAIL_PUBSUB_TOPIC),externalWritesEnabled:process.env.EMAIL_EXTERNAL_WRITES_ENABLED==="true",runtimeMode:process.env.EMAIL_RUNTIME_MODE||"DISABLED"}};
}

export async function ingestInboundEmail(input:{workspaceId:string;connectionId?:string|null;provider:string;providerMessageId:string;providerThreadId?:string|null;from:string;to?:unknown;cc?:unknown;replyTo?:unknown;subject?:string;snippet?:string;bodyText?:string;bodyHtml?:string;attachments?:unknown;classification?:"INBOUND"|"BOUNCE";receivedAt?:string}) {
  const providerMessageId=clean(input.providerMessageId,240); if(!providerMessageId) throw new Error("providerMessageId is required.");
  const from=email(input.from); const receivedAt=input.receivedAt?new Date(input.receivedAt):new Date(); if(Number.isNaN(receivedAt.getTime())) throw new Error("receivedAt is invalid.");
  const prior=await prisma.engageEmailInboundMessage.findUnique({where:{workspaceId_provider_providerMessageId:{workspaceId:input.workspaceId,provider:clean(input.provider,40),providerMessageId}}}); if(prior) return {message:prior,replayed:true};
  const contact=await prisma.whatsAppContact.findFirst({where:{email:{equals:from,mode:"insensitive"}},select:{id:true,email:true}});
  const threadId=clean(input.providerThreadId,240)||null; const classification=input.classification==="BOUNCE"?"BOUNCE":"INBOUND";
  return prisma.$transaction(async tx=>{
    const stored=await tx.engageEmailInboundMessage.create({data:{workspaceId:input.workspaceId,connectionId:clean(input.connectionId,100)||null,provider:clean(input.provider,40),providerMessageId,providerThreadId:threadId,contactId:contact?.id??null,fromAddress:from,toRecipients:json(arr(input.to)),ccRecipients:json(arr(input.cc)),replyTo:input.replyTo?json(input.replyTo):Prisma.JsonNull,subject:clean(input.subject,500),snippet:clean(input.snippet,1000)||null,bodyText:clean(input.bodyText,100000)||null,bodyHtml:clean(input.bodyHtml,200000)||null,attachments:json(arr(input.attachments)),classification,receivedAt}});
    if(classification==="BOUNCE") {
      const sent=threadId?await tx.engageEmailMessage.findFirst({where:{workspaceId:input.workspaceId,OR:[{providerMessageId},{providerThreadId:threadId}]},orderBy:{createdAt:"desc"}}):await tx.engageEmailMessage.findFirst({where:{workspaceId:input.workspaceId,providerMessageId},orderBy:{createdAt:"desc"}});
      if(sent){await tx.engageEmailMessage.update({where:{id:sent.id},data:{status:"BOUNCED",lastError:"Provider reported a bounce."}}); await tx.engageEmailAnalyticsEvent.create({data:{workspaceId:input.workspaceId,messageId:sent.id,inboundMessageId:stored.id,contactId:contact?.id??null,eventType:"BOUNCED",provider:clean(input.provider,40),eventKey:eventKey(["bounce",stored.id]),occurredAt:receivedAt}}); if(contact?.id) await enqueueEmailAutomationEvent(tx,{workspaceId:input.workspaceId,sourceEventId:stored.id,trigger:"EMAIL_BOUNCED",contactId:contact.id,payload:{inboundMessageId:stored.id,messageId:sent.id,providerMessageId}});}
    } else {
      await tx.engageEmailAnalyticsEvent.create({data:{workspaceId:input.workspaceId,inboundMessageId:stored.id,contactId:contact?.id??null,eventType:"RECEIVED",provider:clean(input.provider,40),eventKey:eventKey(["received",stored.id]),occurredAt:receivedAt}});
      if(contact?.id) await enqueueEmailAutomationEvent(tx,{workspaceId:input.workspaceId,sourceEventId:stored.id,trigger:"EMAIL_RECEIVED",relatedTriggers:[],contactId:contact.id,payload:{inboundMessageId:stored.id,subject:stored.subject,fromAddress:from,providerThreadId:threadId}});
      const sent=threadId?await tx.engageEmailMessage.findFirst({where:{workspaceId:input.workspaceId,providerThreadId:threadId,status:{in:["SENT","DELIVERED"]}},orderBy:{sentAt:"desc"}}):null;
      if(sent&&contact?.id){await tx.engageEmailAnalyticsEvent.create({data:{workspaceId:input.workspaceId,messageId:sent.id,inboundMessageId:stored.id,contactId:contact.id,eventType:"REPLIED",provider:clean(input.provider,40),eventKey:eventKey(["reply",stored.id]),occurredAt:receivedAt}}); await enqueueEmailAutomationEvent(tx,{workspaceId:input.workspaceId,sourceEventId:stored.id,trigger:"EMAIL_REPLIED",contactId:contact.id,payload:{inboundMessageId:stored.id,messageId:sent.id,providerThreadId:threadId}}); await supersedePendingEmailAutomationEvents(tx,{workspaceId:input.workspaceId,trigger:"NO_REPLY",contactId:contact.id});}
    }
    return {message:stored,replayed:false};
  });
}

export async function enqueueEmailWebhookAutomationEvent(input:{workspaceId:string;sourceEventId:string;contactId:string;payload?:unknown}) {
  const contact=await prisma.whatsAppContact.findUnique({where:{id:input.contactId},select:{id:true}}); if(!contact) throw new Error("Webhook contact was not found.");
  return prisma.$transaction(async tx=>enqueueEmailAutomationEvent(tx,{workspaceId:input.workspaceId,sourceEventId:clean(input.sourceEventId,200)||randomUUID(),trigger:"WEBHOOK",contactId:input.contactId,payload:(input.payload&&typeof input.payload==="object"&&!Array.isArray(input.payload)?input.payload:{}) as Record<string,unknown>}));
}

export async function createEmailCampaign(input:{workspaceId:string;actorUserId:string;name:unknown;purpose?:unknown;templateId:unknown;templateVersionId:unknown;senderIdentityId?:unknown;throttlePerHour?:unknown;frequencyCapPerDay?:unknown;scheduledAt?:unknown;recipients?:unknown}) {
  const name=clean(input.name,160); if(name.length<3) throw new Error("Campaign name is required."); const templateId=clean(input.templateId,100), templateVersionId=clean(input.templateVersionId,100); if(!templateId||!templateVersionId) throw new Error("Pinned approved template is required.");
  const purpose=clean(input.purpose,30).toUpperCase()==="TRANSACTIONAL"?"TRANSACTIONAL":"MARKETING"; const scheduledAt=clean(input.scheduledAt,50)?new Date(clean(input.scheduledAt,50)):null; if(scheduledAt&&Number.isNaN(scheduledAt.getTime())) throw new Error("scheduledAt is invalid.");
  const raw=arr(input.recipients).slice(0,5000); const recipients=raw.map((v:any)=>({email:email(v?.email),name:clean(v?.name,160)||null,contactId:clean(v?.contactId,100)||null})); const seen=new Set<string>(); const unique=recipients.filter(x=>!seen.has(x.email)&&seen.add(x.email));
  return prisma.$transaction(async tx=>{const campaign=await tx.engageEmailCampaign.create({data:{workspaceId:input.workspaceId,name,status:scheduledAt?"SCHEDULED":"DRAFT",purpose,templateId,templateVersionId,senderIdentityId:clean(input.senderIdentityId,100)||null,segment:json({source:"EXPLICIT_RECIPIENTS",count:unique.length}),throttlePerHour:int(input.throttlePerHour,100,1,5000),frequencyCapPerDay:int(input.frequencyCapPerDay,1,1,20),scheduledAt,createdById:input.actorUserId}}); for(const r of unique){await tx.engageEmailCampaignRecipient.create({data:{workspaceId:input.workspaceId,campaignId:campaign.id,contactId:r.contactId,email:r.email,name:r.name,status:"PENDING",idempotencyKey:`campaign:${campaign.id}:${eventKey([r.email]).slice(0,40)}`,scheduledAt}});} return campaign;});
}

async function assertCampaignRecipientAllowed(workspaceId:string,purpose:string,recipient:{contactId:string|null;email:string},frequencyCapPerDay:number){ if(purpose!=="MARKETING") return; if(!recipient.contactId) throw new Error("Marketing recipient must map to a contact."); const contact=await prisma.whatsAppContact.findUnique({where:{id:recipient.contactId},select:{consentStatus:true}}); if(!contact||contact.consentStatus!=="OPTED_IN") throw new Error("Marketing recipient is not opted in."); const suppression=await prisma.engageCustomerSuppression.findFirst({where:{workspaceId,customerRef:recipient.contactId,revokedAt:null,startsAt:{lte:new Date()},OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}],AND:[{OR:[{channel:null},{channel:"EMAIL"}]}]}}); if(suppression) throw new Error("Recipient is suppressed for email."); const since=new Date(Date.now()-86400000); const count=await prisma.engageEmailAnalyticsEvent.count({where:{workspaceId,contactId:recipient.contactId,eventType:"CAMPAIGN_SENT",occurredAt:{gte:since}}}); if(count>=frequencyCapPerDay) throw new Error("Recipient frequency cap reached."); }

export async function dispatchEmailCampaignBatch(input:{workspaceId:string;campaignId:string;actorUserId:string;limit?:number}) {
  const campaign=await prisma.engageEmailCampaign.findFirst({where:{id:input.campaignId,workspaceId:input.workspaceId}}); if(!campaign) throw new Error("Campaign not found."); if(!["SCHEDULED","ACTIVE"].includes(campaign.status)) throw new Error("Campaign must be SCHEDULED or ACTIVE."); if(campaign.scheduledAt&&campaign.scheduledAt>new Date()) return {processed:0,failed:0,waiting:true};
  const take=Math.min(int(input.limit,Math.max(1,Math.floor(campaign.throttlePerHour/12)),1,100),100); const rows=await prisma.engageEmailCampaignRecipient.findMany({where:{workspaceId:input.workspaceId,campaignId:campaign.id,status:"PENDING",OR:[{scheduledAt:null},{scheduledAt:{lte:new Date()}}]},orderBy:{createdAt:"asc"},take}); let processed=0,failed=0;
  if(campaign.status==="SCHEDULED") await prisma.engageEmailCampaign.update({where:{id:campaign.id},data:{status:"ACTIVE",startedAt:campaign.startedAt??new Date()}});
  for(const row of rows){try{await assertCampaignRecipientAllowed(input.workspaceId,campaign.purpose,row,campaign.frequencyCapPerDay); const result=await new ManualEmailSendService().send({workspaceId:input.workspaceId,templateId:campaign.templateId,templateVersionId:campaign.templateVersionId,automationSenderIdentityId:campaign.senderIdentityId,to:[{email:row.email,...(row.name?{name:row.name}:{})}],variables:{contactId:row.contactId??"",campaignName:campaign.name},idempotencyKey:row.idempotencyKey,actorUserId:input.actorUserId,deliveryContext:"AUTOMATION"}); await prisma.$transaction(async tx=>{await tx.engageEmailCampaignRecipient.update({where:{id:row.id},data:{status:result.message.externalRequestSent?"SENT":"DRY_RUN",messageId:result.message.id,sentAt:result.message.externalRequestSent?new Date():null,lastError:null}}); await tx.engageEmailAnalyticsEvent.upsert({where:{workspaceId_eventKey:{workspaceId:input.workspaceId,eventKey:eventKey(["campaign",row.id,result.message.id])}},update:{},create:{workspaceId:input.workspaceId,messageId:result.message.id,campaignId:campaign.id,contactId:row.contactId,eventType:result.message.externalRequestSent?"CAMPAIGN_SENT":"CAMPAIGN_DRY_RUN",provider:null,eventKey:eventKey(["campaign",row.id,result.message.id]),metadata:json({recipient:row.email}),occurredAt:new Date()}});}); processed++;}catch(e){failed++;await prisma.engageEmailCampaignRecipient.update({where:{id:row.id},data:{status:"FAILED",lastError:e instanceof Error?e.message:"Campaign dispatch failed."}});}}
  const remaining=await prisma.engageEmailCampaignRecipient.count({where:{campaignId:campaign.id,status:"PENDING"}}); if(remaining===0) await prisma.engageEmailCampaign.update({where:{id:campaign.id},data:{status:"COMPLETED",completedAt:new Date()}}); return {processed,failed,remaining};
}

export async function setCampaignStatus(input:{workspaceId:string;campaignId:string;status:"ACTIVE"|"PAUSED"|"CANCELLED"}){const row=await prisma.engageEmailCampaign.findFirst({where:{id:input.campaignId,workspaceId:input.workspaceId}}); if(!row) throw new Error("Campaign not found."); return prisma.engageEmailCampaign.update({where:{id:row.id},data:{status:input.status,...(input.status==="PAUSED"?{pausedAt:new Date()}:{})}});}
export async function listEmailCampaigns(workspaceId:string){return prisma.engageEmailCampaign.findMany({where:{workspaceId},orderBy:{updatedAt:"desc"},take:100,include:{_count:{select:{recipients:true}}}});}
export async function createEmailSequence(input:{workspaceId:string;actorUserId:string;name:unknown;purpose?:unknown;steps:unknown}){
  const name=clean(input.name,160);if(name.length<3)throw new Error("Sequence name is required.");
  const steps=arr(input.steps).slice(0,50).map((raw,index)=>{const row=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const delayMinutes=int(row.delayMinutes,index===0?0:60,0,43_200);const templateId=clean(row.templateId,100),templateVersionId=clean(row.templateVersionId,100);if(!templateId||!templateVersionId)throw new Error(`Sequence step ${index+1} requires templateId and templateVersionId.`);return{delayMinutes,templateId,templateVersionId,senderIdentityId:clean(row.senderIdentityId,100)||null};});
  if(!steps.length)throw new Error("Sequence requires at least one step.");
  return prisma.engageEmailSequence.create({data:{workspaceId:input.workspaceId,name,status:"DRAFT",purpose:clean(input.purpose,30).toUpperCase()==="MARKETING"?"MARKETING":"TRANSACTIONAL",steps:json(steps),createdById:input.actorUserId}});
}
export async function listEmailSequences(workspaceId:string){return prisma.engageEmailSequence.findMany({where:{workspaceId},orderBy:{updatedAt:"desc"},take:100,include:{_count:{select:{enrollments:true}}}});}
export async function setEmailSequenceStatus(input:{workspaceId:string;sequenceId:string;status:"ACTIVE"|"PAUSED"|"ARCHIVED"}){const row=await prisma.engageEmailSequence.findFirst({where:{id:input.sequenceId,workspaceId:input.workspaceId}});if(!row)throw new Error("Sequence not found.");return prisma.engageEmailSequence.update({where:{id:row.id},data:{status:input.status}});}
export async function enrollEmailSequence(input:{workspaceId:string;sequenceId:string;contactId?:unknown;email:unknown;name?:unknown}){const sequence=await prisma.engageEmailSequence.findFirst({where:{id:input.sequenceId,workspaceId:input.workspaceId}});if(!sequence||sequence.status!=="ACTIVE")throw new Error("Active sequence not found.");const address=email(input.email);const steps=arr(sequence.steps);const first=steps[0]&&typeof steps[0]==="object"&&!Array.isArray(steps[0])?steps[0] as Record<string,unknown>:{};const nextRunAt=new Date(Date.now()+int(first.delayMinutes,0,0,43_200)*60_000);return prisma.engageEmailSequenceEnrollment.upsert({where:{sequenceId_email:{sequenceId:sequence.id,email:address}},update:{status:"ACTIVE",currentStep:0,nextRunAt,lastError:null,contactId:clean(input.contactId,100)||null,name:clean(input.name,160)||null},create:{workspaceId:input.workspaceId,sequenceId:sequence.id,contactId:clean(input.contactId,100)||null,email:address,name:clean(input.name,160)||null,status:"ACTIVE",currentStep:0,nextRunAt}});}
export async function processDueEmailSequences(limit=50){const due=await prisma.engageEmailSequenceEnrollment.findMany({where:{status:"ACTIVE",nextRunAt:{lte:new Date()},sequence:{status:"ACTIVE"}},include:{sequence:true},orderBy:{nextRunAt:"asc"},take:Math.min(Math.max(limit,1),100)});let processed=0,failed=0,completed=0;for(const enrollment of due){try{const steps=arr(enrollment.sequence.steps);const raw=steps[enrollment.currentStep];if(!raw||typeof raw!=="object"||Array.isArray(raw)){await prisma.engageEmailSequenceEnrollment.update({where:{id:enrollment.id},data:{status:"COMPLETED"}});completed++;continue;}const step=raw as Record<string,unknown>;if(enrollment.sequence.purpose==="MARKETING")await assertCampaignRecipientAllowed(enrollment.workspaceId,"MARKETING",{contactId:enrollment.contactId,email:enrollment.email},1);const result=await new ManualEmailSendService().send({workspaceId:enrollment.workspaceId,templateId:clean(step.templateId,100),templateVersionId:clean(step.templateVersionId,100),automationSenderIdentityId:clean(step.senderIdentityId,100)||null,to:[{email:enrollment.email,...(enrollment.name?{name:enrollment.name}:{})}],variables:{contactId:enrollment.contactId??"",sequenceName:enrollment.sequence.name},idempotencyKey:`sequence:${enrollment.id}:step:${enrollment.currentStep}`,actorUserId:enrollment.sequence.createdById,deliveryContext:"AUTOMATION"});const nextIndex=enrollment.currentStep+1;const nextRaw=steps[nextIndex];const done=!nextRaw;const nextStep=nextRaw&&typeof nextRaw==="object"&&!Array.isArray(nextRaw)?nextRaw as Record<string,unknown>:{};await prisma.$transaction(async tx=>{await tx.engageEmailSequenceEnrollment.update({where:{id:enrollment.id},data:done?{status:"COMPLETED",currentStep:nextIndex,lastError:null}:{currentStep:nextIndex,nextRunAt:new Date(Date.now()+int(nextStep.delayMinutes,60,0,43_200)*60_000),lastError:null}});await tx.engageEmailAnalyticsEvent.upsert({where:{workspaceId_eventKey:{workspaceId:enrollment.workspaceId,eventKey:eventKey(["sequence",enrollment.id,String(enrollment.currentStep),result.message.id])}},update:{},create:{workspaceId:enrollment.workspaceId,messageId:result.message.id,contactId:enrollment.contactId,eventType:result.message.externalRequestSent?"SEQUENCE_SENT":"SEQUENCE_DRY_RUN",provider:null,eventKey:eventKey(["sequence",enrollment.id,String(enrollment.currentStep),result.message.id]),metadata:json({sequenceId:enrollment.sequenceId,step:enrollment.currentStep,email:enrollment.email}),occurredAt:new Date()}});});processed++;if(done)completed++;}catch(e){failed++;await prisma.engageEmailSequenceEnrollment.update({where:{id:enrollment.id},data:{status:"FAILED",lastError:e instanceof Error?e.message:"Sequence execution failed."}});}}return{processed,failed,completed};}
export async function processDueEmailCampaigns(limit=20){const rows=await prisma.engageEmailCampaign.findMany({where:{status:{in:["ACTIVE","SCHEDULED"]},OR:[{scheduledAt:null},{scheduledAt:{lte:new Date()}}]},orderBy:{scheduledAt:"asc"},take:Math.min(Math.max(limit,1),50)});const results=[];for(const campaign of rows){results.push({campaignId:campaign.id,...await dispatchEmailCampaignBatch({workspaceId:campaign.workspaceId,campaignId:campaign.id,actorUserId:campaign.createdById})});}return results;}
export async function recordEmailAnalyticsEvent(input:{messageId:string;eventType:"OPENED"|"CLICKED"|"DELIVERED";metadata?:unknown}){
  const message=await prisma.engageEmailMessage.findUnique({where:{id:input.messageId}});
  if(!message)throw new Error("Email message not found.");
  const contactId=await resolveWorkspaceSafeTrackingContactId({workspaceId:message.workspaceId,messageId:message.id});
  const suffix=input.eventType==="CLICKED"?eventKey([JSON.stringify(input.metadata??{})]).slice(0,20):"first";
  const key=eventKey(["engagement",input.eventType,message.id,suffix]);
  await prisma.engageEmailAnalyticsEvent.upsert({
    where:{workspaceId_eventKey:{workspaceId:message.workspaceId,eventKey:key}},
    update:contactId?{contactId}:{},
    create:{
      workspaceId:message.workspaceId,
      messageId:message.id,
      contactId,
      eventType:input.eventType,
      provider:null,
      eventKey:key,
      metadata:input.metadata?json(input.metadata):Prisma.JsonNull,
      occurredAt:new Date(),
    },
  });
  if(input.eventType==="DELIVERED"&&message.status==="SENT")await prisma.engageEmailMessage.update({where:{id:message.id},data:{status:"DELIVERED"}});
  return{workspaceId:message.workspaceId};
}
export async function emailAnalyticsOverview(workspaceId:string){const since=new Date(Date.now()-30*86400000);const [events,campaignRecipients,inbound]=await Promise.all([prisma.engageEmailAnalyticsEvent.groupBy({by:["eventType"],where:{workspaceId,occurredAt:{gte:since}},_count:{_all:true}}),prisma.engageEmailCampaignRecipient.groupBy({by:["status"],where:{workspaceId},_count:{_all:true}}),prisma.engageEmailInboundMessage.count({where:{workspaceId,receivedAt:{gte:since}}})]);return{windowDays:30,events:Object.fromEntries(events.map(x=>[x.eventType,x._count._all])),campaignRecipients:Object.fromEntries(campaignRecipients.map(x=>[x.status,x._count._all])),inbound};}
